#:schema node_modules/wrangler/config-schema.json
name = "career-craft"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
minify = true

[vars]
NEXTJS_ENV = "production"

[[assets]]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

# If you want to use Cloudflare KV, D1, or R2, you can add them here:
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-db"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
